name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t grantcthomas/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true grantcthomas/react-test npm test

      - name: Set Service Key
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: muli-k8s-434917

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: muli-cluster
          location: us-west1-a

      - name: Build
        run: |-
          docker build -t grantcthomas/multi-client-k8s-gh:latest -t grantcthomas/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t grantcthomas/multi-server-k8s-pgfix-gh:latest -t grantcthomas/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t grantcthomas/multi-worker-k8s-gh:latest -t grantcthomas/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push grantcthomas/multi-client-k8s-gh:latest
          docker push grantcthomas/multi-server-k8s-pgfix-gh:latest
          docker push grantcthomas/multi-worker-k8s-gh:latest

          docker push grantcthomas/multi-client-k8s-gh:${{ env.SHA }}
          docker push grantcthomas/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push grantcthomas/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=grantcthomas/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=grantcthomas/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=grantcthomas/multi-worker-k8s-gh:${{ env.SHA }}
